version: '2'
services:
  ovn1:
    image: ovn_lab:v2 
    container_name: ovn1
    hostname: ovn1
    command: bash -c 'while true;do sleep 10;done' 
    privileged: true
    environment:
      TERM: linux
      MY_IP: 10.10.0.10
    ports:
      - "16640:6640"
      - "16641:6641"
      - "16642:6642" 
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.10 
    volumes:
      - .:/root/ovn_lab
  ovn2:
    image: ovn_lab:v2
    container_name: ovn2
    hostname: ovn2
    command: bash -c 'while true;do sleep 10;done'
    privileged: true
    environment:
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.20
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.20
    volumes:
      - .:/root/ovn_lab
     

networks:
  ovnnet_local:
    external: true
    
