version: '2'
services:
  ovn-controller:
    image: ovn_lab:v2 
    container_name: ovn-controller
    hostname: ovn-controller
    command: bash -c 'while true;do sleep 10;done' 
    privileged: true
    environment:
      TERM: linux
      MY_IP: 10.10.0.10
    ports:
      - "16640:6640"
      - "16641:6641"
      - "16642:6642" 
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.10 
    volumes:
      - .:/root
  ovn-gw1:
    image: ovn_lab:v2
    container_name: ovn-gw1
    hostname: ovn-gw1
    command: bash -c 'while true;do sleep 10;done'
    privileged: true
    environment: 
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.20
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.20
      ovnnet_outer:
        ipv4_address: 10.20.0.20
    volumes:
      - .:/root
  ovn-gw2:
    image: ovn_lab:v2
    container_name: ovn-gw2
    hostname: ovn-gw2
    command: bash -c 'while true;do sleep 10;done'
    privileged: true
    environment: 
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.30
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.30
      ovnnet_outer:
        ipv4_address: 10.20.0.30
    volumes:
      - .:/root
  ovn-computer1:
    image: ovn_lab:v2
    container_name: ovn-computer1
    hostname: ovn-computer1
    command: bash -c 'while true;do sleep 10;done'
    privileged: true
    environment:
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.40
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.40
    volumes:
      - .:/root
  ovn-computer2:
    image: ovn_lab:v2
    container_name: ovn-computer2
    hostname: ovn-computer2
    command: bash -c 'while true;do sleep 10;done'
    privileged: true
    environment:
      TERM: linux
      OVN_SERVER: 10.10.0.10
      MY_IP: 10.10.0.50
    networks:
      ovnnet_local:
        ipv4_address: 10.10.0.50
    volumes:
      - .:/root  


networks:
  ovnnet_local:
    external: true
  ovnnet_outer:
    external: true
    
